// Build every non-draft deck in decks.json, in manifest order.
//
// The first one takes the site root and the rest hang off it, and it must go
// first: Vite empties the output directory, so building the root last would
// take the others with it. BASE defaults to "/" for a local build; CI passes
// the repository path. A deck marked "draft": true is generated by
// `npm run decks` but never built and never published.
import { readFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

const BASE = process.env.BASE || '/'
const decks = JSON.parse(readFileSync('decks.json', 'utf8')).decks.filter(d => !d.draft)

decks.forEach((d, i) => {
  const name = d.out.replace(/\.md$/, '')
  const [base, out] = i === 0 ? [BASE, 'dist'] : [`${BASE}${name}/`, `dist/${name}`]
  console.log(`\n▸ ${d.out}  base ${base}  ->  ${out}`)
  execFileSync('npx', ['slidev', 'build', d.out, '--base', base, '--out', out], { stdio: 'inherit' })
})
console.log(`\n${decks.length} presentaciones construidas` +
  (JSON.parse(readFileSync('decks.json', 'utf8')).decks.some(d => d.draft)
    ? '  (hay borradores, que no se construyen)' : ''))
